apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: PROJECT_ID
  namespace: PROJECT_NAMESPACE
spec:
  maxReplicas: 2
  minReplicas: 1
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
    scaleUp:
      stabilizationWindowSeconds: 60
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: PROJECT_ID
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
